version: "3.7"
services:
  senha_valida-api:
    image: netomantonio/senha-valida-api:1.0.0
    container_name: senha-valida-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
